image: Visual Studio 2017
build_script:
  - ps: .\build.ps1
test: off
after_test:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "MyProject_coverage.xml"
