language: csharp
sudo: required
dist: trusty
mono: beta
dotnet: 2.0.0
os:
  - linux
# env:
#   global:
#     secure: m2PtYwYOhaK0uFMZ19ZxApZwWZeAIq1dS//jx/5I3txpIWD+TfycQMAWYxycFJ/GJkeVF29P4Zz1uyS2XKKjPJpp2Pds98FNQyDv3OftpLAVa0drsjfhurVlBmSdrV7GH6ncKfvhd+h7KVK5vbZc+NeR4dH7eNvN/jraS//AMJg=

# windows subsystem for linux doesn't seem to chmod properly when on a windows drive :(
script:
  - chmod 755 ./build.sh
  - ./build.sh
