language: csharp
sudo: required
dist: trusty
mono: latest
dotnet: 2.0.0
os:
  - linux
  - osx
before_install:
  - git fetch --unshallow
cache:
  directories:
    - tools
script:
  - chmod 755 ./build.sh
  - ./build.sh
